CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image_url VARCHAR(511) NOT NULL,
    price_per_month FLOAT NOT NULL,
    category VARCHAR(50),
    mileage FLOAT,
    transmission VARCHAR(50),
    fuel_type VARCHAR(50),
    power_in_kw VARCHAR(50),
    seats INT,
    doors INT,
    engine_capacity_in_cm3 FLOAT,
    gears INT,
    cylinders INT,
    curb_weight_in_kg FLOAT,
    latitude FLOAT,
    longitude FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
